spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5432}/${DB_NAME:v_beta}
spring.datasource.username=${SQL_USERNAME}
spring.datasource.password=${SQL_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

firebase.credentials.path=${FIREBASE_CREDENTIALS_PATH:./firebase-credentials.json}

spring.cloud.gcp.project-id=${GCP_PROJECT_ID:None}
spring.cloud.gcp.credentials.location=file:${GOOGLE_SERVICE_CREDENTIALS_PATH:./google-account-credential.json}

app.public-bucket-name=${STORAGE_PUBLIC_BUCKET_NAME:None}
gcp.signed-url.expiration-minutes=5