CREATE TABLE IF NOT EXISTS Gym_Role (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_type VARCHAR(25) NOT NULL
);

CREATE TABLE IF NOT EXISTS Gym_Action(
    action_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_definition varchar(50)
);

CREATE TABLE IF NOT EXISTS Role_Permission(
    role_id BIGINT NOT NULL,
    action_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, action_id),
    FOREIGN KEY (role_id) REFERENCES Gym_Role (role_id),
    FOREIGN KEY (action_id) REFERENCES Gym_Action (action_id)
);

CREATE TABLE IF NOT EXISTS User_Account(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(25) NOT NULL,
    email VARCHAR(225) NOT NULL,
    firebase_uid VARCHAR(128) NOT NULL UNIQUE,
    gym_role_id BIGINT,
    FOREIGN KEY (gym_role_id) REFERENCES Gym_Role (role_id)
);


CREATE TABLE IF NOT EXISTS Climbing_Grade(
    grade_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Wall_Section(
    wall_section_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    info VARCHAR(250),
    wall_section_name VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS Climbing_Problem(
    problem_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hold_color VARCHAR(25) NOT NULL,
    info VARCHAR(250),
    lifecycle_status VARCHAR(25),
    create_date TIMESTAMP,
    wall_section_id BIGINT,
    assigned_grade_id BIGINT,
    FOREIGN KEY (wall_section_id) REFERENCES Wall_Section (wall_section_id),
    FOREIGN KEY (assigned_grade_id) REFERENCES Climbing_Grade (grade_id)
);


CREATE TYPE discussion_kind AS ENUM('COMMENT', 'BETA');

CREATE TABLE IF NOT EXISTS Discussion_Root(
    discussion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_discussion_id BIGINT,
    problem_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    discussion_type discussion_kind NOT NULL,
    create_at TIMESTAMP,
    deleted_by BIGINT,
    deleted_reason VARCHAR(100),
    deleted_at TIMESTAMP,

    CONSTRAINT fk_discussion_parent
        FOREIGN KEY (parent_discussion_id) REFERENCES Discussion_Root (discussion_id),
    CONSTRAINT fk_discussion_problem
        FOREIGN KEY (problem_id) REFERENCES Climbing_Problem (problem_id),
    CONSTRAINT fk_discussion_user
        FOREIGN KEY (user_id) REFERENCES User_Account (user_id),
    CONSTRAINT fk_discussion_deleted_by
        FOREIGN KEY (deleted_by) REFERENCES User_Account (user_id),

    CONSTRAINT chk_not_self_parent
        CHECK (parent_discussion_id IS NULL OR parent_discussion_id <> discussion_id)
);

CREATE INDEX IF NOT EXISTS idx_discussion_root_problem_created_id
    ON Discussion_Root (problem_id, create_at ASC, discussion_id ASC);

CREATE INDEX IF NOT EXISTS idx_discussion_root_parent_created_id
    ON Discussion_Root (parent_discussion_id, create_at DESC, discussion_id DESC);

CREATE INDEX IF NOT EXISTS idx_discussion_root_problem_parent_created_id
    ON Discussion_Root (problem_id, parent_discussion_id, create_at DESC, discussion_id DESC);

CREATE TABLE IF NOT EXISTS User_Perceive_Grade(
    user_id BIGINT NOT NULL,
    grade_id BIGINT NOT NULL,
    problem_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, problem_id),
    FOREIGN KEY (user_id) REFERENCES User_Account (user_id),
    FOREIGN KEY (problem_id) REFERENCES Climbing_Problem (problem_id),
    FOREIGN KEY (grade_id) REFERENCES Climbing_Grade (grade_id)
);

CREATE TABLE IF NOT EXISTS Solution_Beta(
    beta_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discussion_id BIGINT UNIQUE NOT NULL,
    beta_name VARCHAR(250) NOT NULL,
    video_url VARCHAR(250) NOT NULL UNIQUE,
    create_date TIMESTAMP,

    CONSTRAINT fk_discussion_root
        FOREIGN KEY (discussion_id) REFERENCES Discussion_Root(discussion_id)
);

CREATE TABLE IF NOT EXISTS Discussion_Comment(
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discussion_id BIGINT UNIQUE NOT NULL,
    info VARCHAR(250),
    create_date TIMESTAMP,

    CONSTRAINT fk_discussion_root
        FOREIGN KEY (discussion_id) REFERENCES Discussion_Root (discussion_id)
);

CREATE TYPE report_status AS Enum(
    'OPEN',
    'DISMISSED',
    'CONTENT_REMOVED',
    'APPEAL_PENDING',
    'CONTENT_RESTORED',
    'APPEAL_DENIED'
    );

CREATE TABLE IF NOT EXISTS Report_Category(
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(40) NOT NULL UNIQUE,
    weight INTEGER NOT NULL UNIQUE CHECK (weight > 0)
);

INSERT INTO Report_Category (category_name, weight) VALUES
    ('INAPPROPRIATE_CONTENT', 4),
    ('HARASSMENT_BULLYING', 3),
    ('SPAM', 2),
    ('OFF_TOPIC', 1);


CREATE TYPE report_target_type AS ENUM (
    'DISCUSSION',
    'WALL_SECTION',
    'CLIMBING_PROBLEM',
    'USER_ACCOUNT'
    );

CREATE TYPE moderate_action_type AS ENUM(
    'REPORT_DISMISSED',
    'CONTENT_REMOVED',
    'APPEAL_APPROVED',
    'APPEAL_DENIED'
    );


CREATE TABLE IF NOT EXISTS Report(
    report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id BIGINT NOT NULL,
    report_reason VARCHAR(250) NOT NULL,
    category_id BIGINT NOT NULL,
    target_type report_target_type NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    report_status report_status NOT NULL DEFAULT 'OPEN',
    resolved_at TIMESTAMPTZ,

    discussion_id BIGINT,
    problem_id BIGINT,
    wall_section_id BIGINT,
    user_id BIGINT,

    CONSTRAINT fk_reporter_id
        FOREIGN KEY (reporter_id) REFERENCES user_account(user_id),
    CONSTRAINT fk_report_category
        FOREIGN KEY (category_id) REFERENCES Report_Category(category_id),
    CONSTRAINT fk_report_discussion
        FOREIGN KEY (discussion_id) REFERENCES Discussion_Root(discussion_id),
    CONSTRAINT fk_report_problem
        FOREIGN KEY (problem_id) REFERENCES Climbing_Problem(problem_id),
    CONSTRAINT fk_report_wall_section
        FOREIGN KEY (wall_section_id) REFERENCES Wall_Section(wall_section_id),
    CONSTRAINT fk_report_user
        FOREIGN KEY (user_id) REFERENCES User_Account(user_id),

    CONSTRAINT chk_one_report_target CHECK(
        (target_type = 'DISCUSSION' AND discussion_id IS NOT NULL AND problem_id IS NULL
            AND wall_section_id is NULL AND user_id IS NULL)
            OR
        (target_type = 'WALL_SECTION' AND wall_section_id IS NOT NULL AND discussion_id IS NULL
            AND problem_id IS NULL AND user_id IS NULL)
            OR
        (target_type = 'CLIMBING_PROBLEM' AND problem_id IS NOT NULL AND discussion_id IS NULL
            AND wall_section_id IS NULL AND user_id IS NULL)
            OR
        (target_type = 'USER_ACCOUNT' AND user_id IS NOT NULL AND discussion_id IS NULL
            AND wall_section_id IS NULL AND problem_id IS NULL)
        )
);

CREATE UNIQUE INDEX uq_one_open_report_per_user_target
    ON Report(
        reporter_id,
        target_type,
        COALESCE(discussion_id, 0),
        COALESCE(problem_id, 0),
        COALESCE(wall_section_id, 0),
        COALESCE(user_id, 0)
        )
    WHERE report_status = 'OPEN';

CREATE TYPE appeal_status AS Enum(
    'OPEN',
    'APPROVED',
    'DENIED'
    );

CREATE TABLE IF NOT EXISTS Appeal(
    appeal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT NOT NULL UNIQUE,
    appeal_user_id BIGINT NOT NULL,
    reason VARCHAR(250) NOT NULL,
    status appeal_status NOT NULL DEFAULT 'OPEN',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMPTZ,
    reviewed_by BIGINT,
    admin_note VARCHAR(255),

    CONSTRAINT fk_report
        FOREIGN KEY (report_id) REFERENCES report(report_id),
    CONSTRAINT fk_appeal_user
        FOREIGN KEY (appeal_user_id) REFERENCES user_account(user_id),
    CONSTRAINT fk_appeal_reviewer
        FOREIGN KEY (reviewed_by) REFERENCES User_Account(user_id)
);

CREATE TABLE IF NOT EXISTS Moderation_Action (
    action_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT NOT NULL,
    admin_user_id BIGINT NOT NULL,
    action_type moderate_action_type NOT NULL,
    admin_notes VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_moderate_report
        FOREIGN KEY (report_id) REFERENCES Report(report_id),
    CONSTRAINT fk_moderate_admin
        FOREIGN KEY (admin_user_id) REFERENCES User_Account(user_id)
);

CREATE TABLE IF NOT EXISTS Event_Type(
    event_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type_name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(100)
);


CREATE TYPE event_target_type AS ENUM(
    'REPORT',
    'DISCUSSION',
    'CLIMBING_PROBLEM',
    'WALL_SECTION',
    'USER_ACCOUNT'
    );

CREATE TABLE IF NOT EXISTS Events(
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type_id BIGINT NOT NULL,
    actor_user_id BIGINT,
    target_type event_target_type NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    report_id BIGINT,
    discussion_id BIGINT,
    problem_id BIGINT,
    wall_section_id BIGINT,
    user_id BIGINT,


    CONSTRAINT fk_event_type
        FOREIGN KEY (event_type_id) REFERENCES event_type (event_type_id),
    CONSTRAINT fk_actor_id
        FOREIGN KEY (actor_user_id) REFERENCES User_Account(user_id),
    CONSTRAINT fk_event_report
        FOREIGN KEY (report_id) REFERENCES Report(report_id),
    CONSTRAINT fk_event_discussion
        FOREIGN KEY (discussion_id) REFERENCES Discussion_Root(discussion_id),
    CONSTRAINT fk_event_problem
        FOREIGN KEY (problem_id) REFERENCES Climbing_Problem(problem_id),
    CONSTRAINT fk_event_wall_section
        FOREIGN KEY (wall_section_id) REFERENCES Wall_Section(wall_section_id),
    CONSTRAINT fk_event_user
        FOREIGN KEY (user_id) REFERENCES User_Account(user_id),

    CONSTRAINT chk_one_event_target CHECK(
        (target_type = 'REPORT' AND report_id IS NOT NULL AND problem_id IS NULL
            AND discussion_id IS NULL AND wall_section_id IS NULL AND user_id IS NULL)
            OR
        (target_type = 'DISCUSSION' AND discussion_id IS NOT NULL AND problem_id IS NULL
            AND wall_section_id is NULL AND user_id IS NULL AND report_id IS NULL)
            OR
        (target_type = 'WALL_SECTION' AND wall_section_id IS NOT NULL AND discussion_id IS NULL
            AND problem_id IS NULL AND user_id IS NULL AND report_id IS NULL)
            OR
        (target_type = 'CLIMBING_PROBLEM' AND problem_id IS NOT NULL AND discussion_id IS NULL
            AND wall_section_id IS NULL AND user_id IS NULL AND report_id IS NULL)
            OR
        (target_type = 'USER_ACCOUNT' AND user_id IS NOT NULL AND discussion_id IS NULL
            AND wall_section_id IS NULL AND problem_id IS NULL AND report_id IS NULL)
        )
);

CREATE TABLE IF NOT EXISTS Notification(
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    recipient_user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMPTZ,

    CONSTRAINT fk_event_id
        FOREIGN KEY (event_id) REFERENCES events (event_id),
    CONSTRAINT fk_recipient_user
        FOREIGN KEY (recipient_user_id) REFERENCES user_account(user_id),

    UNIQUE(event_id, recipient_user_id)
);

CREATE INDEX idx_report_queue ON Report (report_status, created_at);
CREATE INDEX idx_notification_recipient ON Notification (recipient_user_id, created_at DESC);


INSERT INTO Gym_Role(role_type)
    VALUES ('CLIMBER'), ('SETTER'), ('ADMIN');

INSERT INTO Gym_Action (action_definition)
    VALUES ('CREATE_BETA'), ('DELETE_BETA'), ('CREATE_COMMENT'), ('DELETE_COMMENT'),
           ('CREATE_PROBLEM'), ('DELETE_PROBLEM'), ('RESET_WALL'), ('CREATE_WALL'), ('DELETE_WALL'),
           ('CHANGE_ROLE'), ('GRADE_PROBLEM'), ('VIEW_ACCOUNTS'), ('MODERATE_REPORT');


INSERT INTO Climbing_Grade(grade)
    VALUES ('VB'), ('V0'), ('V1'), ('V2'), ('V3'), ('V4'),
           ('V5'), ('V6'), ('V7'), ('V8'), ('V9'), ('V10'), ('V11'),
           ('V12'), ('V13'), ('V14'), ('V15'), ('V16'), ('V17');

INSERT INTO Role_Permission (role_id, action_id)
    VALUES (1, 1), (1, 2), (1, 3), (1, 4), (1, 11),
           (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6),
           (2, 7), (2, 11), (3, 1), (3, 2), (3, 3), (3, 4),
           (3, 8), (3, 9), (3, 10), (3, 11), (3, 12), (3, 13), (3, 14);

INSERT INTO Wall_Section (info, wall_section_name)
    VALUES ('This is a test wall section', 'Test Wall');

INSERT INTO Climbing_Problem(hold_color, info, lifecycle_status, create_date, wall_section_id, assigned_grade_id)
    VALUES ('BLACK', 'BLACK VB-V0', 'ACTIVE', NOW(), 1, 1),
           ('RED', 'RED V0-V1', 'ACTIVE', NOW(), 1, 2);

INSERT INTO Climbing_Problem(hold_color, info, lifecycle_status, create_date, wall_section_id, assigned_grade_id)
    VALUES ('BLACK', 'BLACK V8-V9', 'ARCHIVE', NOW(), 1, 10);

INSERT INTO User_Account(username, email, firebase_uid, gym_role_id)
    VALUES ('testUser', 'testUser@gmail.com', 'testFirebaseUid', 1);

INSERT INTO User_Account(username, email, firebase_uid, gym_role_id)
    VALUES ('testSetter', 'testSetter@gmail.com', 'testFirebaseUid2', 2),
           ('testAdmin', 'testAdmin@gmail.com', 'testFirebaseUid3', 3);

INSERT INTO User_Perceive_Grade(user_id, grade_id, problem_id)
    VALUES (1, 3, 1),
           (2, 3, 1),
           (3, 6, 1);


INSERT INTO Event_Type (event_type_name, description) VALUES
    ('REPORT_CREATED', 'A user submitted a content report'),
    ('REPORT_DISMISSED', 'An admin dismissed a report you submitted'),
    ('CONTENT_REMOVED', 'A content that you reported had been removed'),
    ('APPEAL_SUBMITTED', 'A content owner appeal a removal'),
    ('CONTENT_RESTORED', 'An admin restored your content after appeal'),
    ('APPEAL_DENIED', 'An admin denied the appeal');
