spring.config.import=optional:file:../../../.env
spring.cloud.gcp.sql.instance-connection-name=[INSTANCE_CONNECTION_NAME]
spring.cloud.gcp.sql.database-name=[DATABASE_NAME]
spring.datasource.username=[USERNAME]
spring.datasource.password=[PASSWORD]

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#spring.cloud.gcp.storage.bucket-name=[BUCKET_NAME]


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

firebase.credentials.path=${FIREBASE_CREDENTIALS_PATH:./serviceAccountKey.json}
