CREATE TABLE IF NOT EXISTS Gym_Role (
	role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_type VARCHAR(25) NOT NULL
);

CREATE TABLE IF NOT EXISTS Gym_Action(
	action_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_definition varchar(50)
);

CREATE TABLE IF NOT EXISTS Role_Permission(
	role_id BIGINT NOT NULL,
    action_id BIGINT NOT NULL,
	PRIMARY KEY (role_id, action_id),
    FOREIGN KEY (role_id) REFERENCES Gym_Role (role_id),
    FOREIGN KEY (action_id) REFERENCES Gym_Action (action_id)
);

CREATE TABLE IF NOT EXISTS User_Account(
	user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(25) NOT NULL,
    email VARCHAR(225) NOT NULL,
    firebase_uid VARCHAR(128) NOT NULL UNIQUE,
    gym_role_id BIGINT,
    FOREIGN KEY (gym_role_id) REFERENCES Gym_Role (role_id)
);


CREATE TABLE IF NOT EXISTS Climbing_Grade(
	grade_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Wall_Section(
	wall_section_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    info VARCHAR(250),
    wall_section_name VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS Climbing_Problem(
	problem_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hold_color VARCHAR(25) NOT NULL,
    info VARCHAR(250),
    lifecycle_status VARCHAR(25),
    create_date TIMESTAMP,
    wall_section_id BIGINT,
    assigned_grade_id BIGINT,
    FOREIGN KEY (wall_section_id) REFERENCES Wall_Section (wall_section_id),
    FOREIGN KEY (assigned_grade_id) REFERENCES Climbing_Grade (grade_id)
);

CREATE TABLE IF NOT EXISTS User_Perceive_Grade(
	user_id BIGINT NOT NULL,
    grade_id BIGINT NOT NULL,
    problem_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, problem_id),
    FOREIGN KEY (user_id) REFERENCES User_Account (user_id),
    FOREIGN KEY (problem_id) REFERENCES Climbing_Problem (problem_id),
    FOREIGN KEY (grade_id) REFERENCES Climbing_Grade (grade_id)
);

CREATE TYPE discussion_kind AS ENUM('COMMENT', 'BETA');

CREATE TABLE IF NOT EXISTS Discussion_Root(
	discussion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	parent_discussion_id BIGINT,
	problem_id BIGINT NOT NULL,
	user_id BIGINT NOT NULL,
	discussion_type discussion_kind NOT NULL,
	create_at TIMESTAMP,
	deleted_by BIGINT,
	deleted_reason VARCHAR(100),
	deleted_at TIMESTAMP,

	CONSTRAINT fk_discussion_parent
		FOREIGN KEY (parent_discussion_id) REFERENCES Discussion_Root (discussion_id),
	CONSTRAINT fk_discussion_problem
		FOREIGN KEY (problem_id) REFERENCES Climbing_Problem (problem_id),
	CONSTRAINT fk_discussion_user
		FOREIGN KEY (user_id) REFERENCES User_Account (user_id),
	CONSTRAINT fk_discussion_deleted_by
		FOREIGN KEY (deleted_by) REFERENCES User_Account (user_id),

	CONSTRAINT chk_not_self_parent
		CHECK (parent_discussion_id IS NULL OR parent_discussion_id <> discussion_id)
);

CREATE TABLE IF NOT EXISTS Solution_Beta(
                                            beta_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            discussion_id BIGINT UNIQUE NOT NULL,
                                            beta_name VARCHAR(250) NOT NULL,
    video_url VARCHAR(250) NOT NULL UNIQUE,
    create_date TIMESTAMP,

    CONSTRAINT fk_discussion_root
    FOREIGN KEY (discussion_id) REFERENCES Discussion_Root(discussion_id)
    );

CREATE TABLE IF NOT EXISTS Discussion_Comment(
                                                 comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                 discussion_id BIGINT UNIQUE NOT NULL,
                                                 info VARCHAR(250),
    create_date TIMESTAMP,

    CONSTRAINT fk_discussion_root
    FOREIGN KEY (discussion_id) REFERENCES Discussion_Root (discussion_id)
    );


INSERT INTO Gym_Role(role_type)
	VALUES ('CLIMBER'), ('SETTER'), ('ADMIN');
    
INSERT INTO Gym_Action (action_definition)
	VALUES ('CREATE_BETA'), ('DELETE_BETA'), ('CREATE_COMMENT'), ('DELETE_COMMENT'),
    ('CREATE_PROBLEM'), ('DELETE_PROBLEM'), ('RESET_WALL'), ('CREATE_WALL'), ('DELETE_WALL'),
    ('CHANGE_ROLE'), ('GRADE_PROBLEM'), ('VIEW_ACCOUNTS');

INSERT INTO Climbing_Grade(grade) 
	VALUES ('VB'), ('V0'), ('V1'), ('V2'), ('V3'), ('V4'),
	('V5'), ('V6'), ('V7'), ('V8'), ('V9'), ('V10'), ('V11'),
    ('V12'), ('V13'), ('V14'), ('V15'), ('V16'), ('V17');

INSERT INTO Role_Permission (role_id, action_id) 
	VALUES (1, 1), (1, 2), (1, 3), (1, 4), (1, 11),
    (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6),
    (2, 7), (2, 11), (3, 1), (3, 2), (3, 3), (3, 4),
    (3, 8), (3, 9), (3, 10), (3, 11), (3, 12);
    
INSERT INTO Wall_Section (info, wall_section_name) 
	VALUES ('This is a test wall section', 'Test Wall');

INSERT INTO Climbing_Problem(hold_color, info, lifecycle_status, create_date, wall_section_id, assigned_grade_id)
	VALUES ('BLACK', 'BLACK VB-V0', 'ACTIVE', NOW(), 1, 1),
    ('RED', 'RED V0-V1', 'ACTIVE', NOW(), 1, 2);
    
INSERT INTO Climbing_Problem(hold_color, info, lifecycle_status, create_date, wall_section_id, assigned_grade_id)
	VALUES ('BLACK', 'BLACK V8-V9', 'ARCHIVE', NOW(), 1, 10);

INSERT INTO User_Account(username, email, firebase_uid, gym_role_id) 
	VALUES ('testUser', 'testUser@gmail.com', 'testFirebaseUid', 1);
    
INSERT INTO User_Account(username, email, firebase_uid, gym_role_id) 
	VALUES ('testSetter', 'testSetter@gmail.com', 'testFirebaseUid2', 2),
		('testAdmin', 'testAdmin@gmail.com', 'testFirebaseUid3', 3);

INSERT INTO User_Perceive_Grade(user_id, grade_id, problem_id)
	VALUES (1, 3, 1),
		(2, 3, 1),
        (3, 6, 1);
        
